In [1]:
#exemplo utilização
import pandas as pd

In [2]:
#Criando um DataFrame
data = {
    'Nome': ['Ana', 'João', 'Maria'],
    'Idade': [25, 30, 28],
    'Salario': [5000, 7000, 6000]
}
df = pd.DataFrame(data)

In [3]:
print(df.head())

    Nome  Idade  Salario
0    Ana     25     5000
1   João     30     7000
2  Maria     28     6000


In [4]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Nome     3 non-null      object
 1   Idade    3 non-null      int64 
 2   Salario  3 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes
None


In [5]:
print(df.describe())

           Idade  Salario
count   3.000000      3.0
mean   27.666667   6000.0
std     2.516611   1000.0
min    25.000000   5000.0
25%    26.500000   5500.0
50%    28.000000   6000.0
75%    29.000000   6500.0
max    30.000000   7000.0


In [6]:
import numpy as np

In [8]:
#Criando um array
arr = np.array([1, 2, 3, 4, 5])

#operações vetorizadas
print(arr + 10) # soma 10 a cada elemento
print(arr - 1) # subtrai 1 de cada elemento
print(arr * 2) # multiplica cada elemento por 2
print(arr ** 2) # eleva cada elemento por 2
print(arr / 2) # divide cada elemento por 2

[11 12 13 14 15]
[0 1 2 3 4]
[ 2  4  6  8 10]
[ 1  4  9 16 25]
[0.5 1.  1.5 2.  2.5]


In [15]:
# 1 - criação de dados fictícios com NumPy
np.random.seed(42)
meses = np.array(['Jan', 'Fev', 'Mar', 'Abr', 'Mai'])
vendas = np.random.randint(100, 500, size=5)
custos = vendas * np.random.uniform(0.3, 0.7, size=5)
#escolher numero aleatorio randômico

print(meses)
print(vendas)
print(custos)

['Jan' 'Fev' 'Mar' 'Abr' 'Mai']
[202 448 370 206 171]
[108.97160552 162.35854037 134.08718901  66.58608964 110.54644837]


In [16]:
# 2 - Conversão para DataFrame do Pandas
dados = pd.DataFrame({
    'Mes': meses,
    'Vendas (R$)': vendas,
    'Custos (R$)': np.round(custos,2),
    'Clientes': np.random.poisson(lam=50,size=5) #escolher numero aleatorio randômico
})
print(dados)

   Mes  Vendas (R$)  Custos (R$)  Clientes
0  Jan          202       108.97        52
1  Fev          448       162.36        58
2  Mar          370       134.09        43
3  Abr          206        66.59        46
4  Mai          171       110.55        49


In [19]:
dados['Lucro (R$)'] = dados['Vendas (R$)'] - dados['Custos (R$)'] # adição de colouna
print(dados)

   Mes  Vendas (R$)  Custos (R$)  Clientes  Lucro (R$)
0  Jan          202       108.97        52       93.03
1  Fev          448       162.36        58      285.64
2  Mar          370       134.09        43      235.91
3  Abr          206        66.59        46      139.41
4  Mai          171       110.55        49       60.45


In [20]:
dados['Teste (R$)'] = dados['Vendas (R$)'] * dados['Lucro (R$)'] # adição de colouna
print(dados)

   Mes  Vendas (R$)  Custos (R$)  Clientes  Lucro (R$)  Teste (R$)
0  Jan          202       108.97        52       93.03    18792.06
1  Fev          448       162.36        58      285.64   127966.72
2  Mar          370       134.09        43      235.91    87286.70
3  Abr          206        66.59        46      139.41    28718.46
4  Mai          171       110.55        49       60.45    10336.95


In [23]:
dados['Margem %'] = np.round((dados['Lucro (R$)']/ dados['Vendas (R$)']) * 100, 1) #Arredondamento para 1 casa decimal
print(dados)

   Mes  Vendas (R$)  Custos (R$)  Clientes  Lucro (R$)  Teste (R$)  Margem %
0  Jan          202       108.97        52       93.03    18792.06      46.1
1  Fev          448       162.36        58      285.64   127966.72      63.8
2  Mar          370       134.09        43      235.91    87286.70      63.8
3  Abr          206        66.59        46      139.41    28718.46      67.7
4  Mai          171       110.55        49       60.45    10336.95      35.4
